all:
	g++ ./client-phase1.cpp -lpthread -lcrypto -o client-phase1
	g++ ./client-phase2.cpp -lpthread -lcrypto -o client-phase2
	g++ ./client-phase3.cpp -lpthread -lcrypto -o client-phase3
	g++ ./client-phase4.cpp -lpthread -lcrypto -o client-phase4
	g++ ./client-phase5.cpp -lpthread -lcrypto -o client-phase5
